project:
  type: website
  output-dir: docs

website:
  title: "Zander Gordan"
  site-url: https://www.zandergordan.com
  description: "Zander Gordan's personal blog"
  favicon: favicon.ico
  margin-header: subscribe.html
  twitter-card: true
  open-graph: true
  google-analytics: 
    tracking-id: "G-PNM0RM754C"
    anonymize-ip: false
  comments:
    hypothesis: true
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - music.qmd
      - about.qmd
      - demo.qmd
      - icon: github
        href: https://github.com/zandergordan/zandergordan-com
      - icon: rss
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

